//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMastermind.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMastermind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0m[2J[1;1H ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
        /// ³[1;30m ±±  ±±  ±±  ±±[0m ³ É» É»   Ë   ÉÍÍÍÍ ÍÍËÍÍ ÉÍÍÍÍ ÉÍÍÍ» É» É» ÍÍËÍÍ É»  Ë ÉÍÍ»
        /// ÃÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄ´ ºÈË¼º  ÉÊ»  º[7Cº   º[5Cº   º ºÈË¼º   º   ºÈ» º º  È»
        /// ³[1;30m þ þ þ þ[0m ³[1;30m ùùùù[0m ³ º Ê º ÉÊÍÊ» ÈÍÍÍ»   º   ÌÍÍ   ÌÍÍË¼ º Ê º   º   º È»º º   º
        /// ÃÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄ´ º   º º   º[5Cº   º   º[5Cº  º  º   º   º   º  È¹ º  É¼
        /// ³[1;30m þ þ þ þ[0m ³[1;30m ùùùù[0m ³ Ê   Ê Ê   Ê ÍÍÍÍ¼   Ê   ÈÍÍÍÍ Ê  Ê  Ê   Ê ÍÍÊÍÍ Ê   Ê ÈÍÍ¼
        /// ÃÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄ´
        /// ³[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MAIN_ANS {
            get {
                return ResourceManager.GetString("MAIN_ANS", resourceCulture);
            }
        }
    }
}
